export const SET_IMAGE_LABELS = 'SET_IMAGE_LABELS';
export const SET_IMAGE_WEB_LABELS = 'SET_IMAGE_WEB_LABELS';
export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_END_LOADING = 'UI_END_LOADING';