export const SET_IMAGE_LABELS = 'SET_IMAGE_LABELS';
export const SET_IMAGE_WEB_LABELS = 'SET_IMAGE_WEB_LABELS';
export const SET_IMAGE_OBJECTS = 'SET_IMAGE_OBJECTS';
export const SET_IMAGE_TEXT = 'SET_IMAGE_TEXT';
export const SET_IMAGE_PROPERTIES = 'SET_IMAGE_PROPERTIES';
export const SET_IMAGE_SAFE_SEARCH = 'SET_IMAGE_SAFE_SEARCH';
export const ERROR = 'ERROR';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_END_LOADING = 'UI_END_LOADING';